# Generated by Django 3.1 on 2020-08-08 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.data')),
                ('value', models.TextField()),
            ],
            bases=('dashboard.data',),
        ),
        migrations.CreateModel(
            name='RoomInhabited',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.data')),
                ('value', models.BooleanField()),
            ],
            bases=('dashboard.data',),
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.data')),
                ('value', models.FloatField()),
            ],
            bases=('dashboard.data',),
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('last_updated', models.DateTimeField()),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.data')),
            ],
        ),
    ]
